/* ---------------------------------------------------------------------------------------
	This class has been auto-generated by the Sprocket Class Generator. It is recommended
	that you do not modify this file and instead use the fact that it has been generated
	as a partial class to create a separate partial class for storing any custom code that
	you write to extend the functionality of this class.
   --------------------------------------------------------------------------------------- */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data;
using System.Reflection;
using System.Globalization;

using Sprocket;
using Sprocket.Data;
using Sprocket.Utility;

namespace Sprocket.Web.Merchant.PayPal
{
	public partial class PayPalTransactionResponse
	{
		#region Utility Members
		
		private bool isNew = true;
		private bool wasNew = true;

		/// <summary>
		/// Gets or sets whether or not this entity already exists as a record in a database.
		/// This information is useful for knowing whether to perform an INSERT or UPDATE
		/// database operation.
		/// </summary>
		public bool IsNew
		{
			get { return isNew; }
			protected set { isNew = value; }
		}

		/// <summary>
		/// Gets or sets whether or not this entity was constructed as a new entity or from
		/// data that was retrieved from the database. This is useful if we've saved the data,
		/// hence setting IsNew to false, but still need to know if this was a new object so
		/// that we know that we should perform INSERT operations on dependent data, rather than
		/// UPDATE operations.
		/// </summary>
		public bool WasNew
		{
			get { return wasNew; }
			protected set { wasNew = value; }
		}

		internal void SetSaved()
		{
			isNew = false;
		}
		
		#endregion

		#region Fields
		
		protected Guid transactionID = Guid.NewGuid();
		protected string txn_id = "";
		protected string txn_type = null;
		protected decimal? auth_amount = null;
		protected string auth_id = null;
		protected DateTime? auth_exp = null;
		protected string auth_status = null;
		protected decimal? mc_gross_x = null;
		protected decimal? mc_handling_x = null;
		protected int? num_cart_items = null;
		protected string parent_txn_id = null;
		protected DateTime? payment_date = null;
		protected string payment_status = null;
		protected string payment_type = null;
		protected string pending_reason = null;
		protected string reason_code = null;
		protected decimal? remaining_settle = null;
		protected string transaction_entity = null;
		protected string invoice = null;
		protected string memo = null;
		protected decimal? tax = null;
		protected string business = null;
		protected string item_name = null;
		protected string item_number = null;
		protected int? quantity = null;
		protected string receiver_email = null;
		protected string receiver_id = null;
		protected string address_city = null;
		protected string address_country = null;
		protected string address_country_code = null;
		protected string address_name = null;
		protected string address_state = null;
		protected string address_status = null;
		protected string address_street = null;
		protected string address_zip = null;
		protected string first_name = null;
		protected string last_name = null;
		protected string payer_id = null;
		protected string payer_status = null;
		protected string residence_country = null;
		protected decimal? exchange_rate = null;
		protected decimal? mc_fee = null;
		protected decimal? mc_gross = null;
		protected decimal? mc_handlingamount = null;
		protected decimal? mc_shippingamount = null;
		protected decimal? payment_fee = null;
		protected decimal? payment_gross = null;
		protected decimal? settle_amount = null;
		protected string settle_currency = null;
		protected DateTime? subscr_date = null;
		protected DateTime? subscr_effective = null;
		protected string period1 = null;
		protected string period2 = null;
		protected string period3 = null;
		protected decimal? amount1 = null;
		protected decimal? amount2 = null;
		protected decimal? amount3 = null;
		protected decimal? mc_amount1 = null;
		protected decimal? mc_amount2 = null;
		protected decimal? mc_amount3 = null;
		protected string mc_currency = null;
		protected bool? recurring = null;
		protected bool? reattempt = null;
		protected DateTime? retry_at = null;
		protected int? recur_times = null;
		protected string username = null;
		protected string password = null;
		protected string subscr_id = null;
		protected string custom = null;
		
		#endregion

		#region Properties
		
		///<summary>
		///Gets or sets the value for TransactionID
		///</summary>
		public Guid TransactionID
		{
			get { return transactionID; }
			set { transactionID = value; }
		}

		///<summary>
		///Gets or sets the value for Txn_id
		///</summary>
		public string Txn_id
		{
			get { return txn_id; }
			set { txn_id = value; }
		}

		///<summary>
		///Gets or sets the value for Txn_type
		///</summary>
		public string Txn_type
		{
			get { return txn_type; }
			set { txn_type = value; }
		}

		///<summary>
		///Gets or sets the value for Auth_amount
		///</summary>
		public decimal? Auth_amount
		{
			get { return auth_amount; }
			set { auth_amount = value; }
		}

		///<summary>
		///Gets or sets the value for Auth_id
		///</summary>
		public string Auth_id
		{
			get { return auth_id; }
			set { auth_id = value; }
		}

		///<summary>
		///Gets or sets the value for Auth_exp
		///</summary>
		public DateTime? Auth_exp
		{
			get { return auth_exp; }
			set { auth_exp = value; }
		}

		///<summary>
		///Gets or sets the value for Auth_status
		///</summary>
		public string Auth_status
		{
			get { return auth_status; }
			set { auth_status = value; }
		}

		///<summary>
		///Gets or sets the value for Mc_gross_x
		///</summary>
		public decimal? Mc_gross_x
		{
			get { return mc_gross_x; }
			set { mc_gross_x = value; }
		}

		///<summary>
		///Gets or sets the value for Mc_handling_x
		///</summary>
		public decimal? Mc_handling_x
		{
			get { return mc_handling_x; }
			set { mc_handling_x = value; }
		}

		///<summary>
		///Gets or sets the value for Num_cart_items
		///</summary>
		public int? Num_cart_items
		{
			get { return num_cart_items; }
			set { num_cart_items = value; }
		}

		///<summary>
		///Gets or sets the value for Parent_txn_id
		///</summary>
		public string Parent_txn_id
		{
			get { return parent_txn_id; }
			set { parent_txn_id = value; }
		}

		///<summary>
		///Gets or sets the value for Payment_date
		///</summary>
		public DateTime? Payment_date
		{
			get { return payment_date; }
			set { payment_date = value; }
		}

		///<summary>
		///Gets or sets the value for Payment_status
		///</summary>
		public string Payment_status
		{
			get { return payment_status; }
			set { payment_status = value; }
		}

		///<summary>
		///Gets or sets the value for Payment_type
		///</summary>
		public string Payment_type
		{
			get { return payment_type; }
			set { payment_type = value; }
		}

		///<summary>
		///Gets or sets the value for Pending_reason
		///</summary>
		public string Pending_reason
		{
			get { return pending_reason; }
			set { pending_reason = value; }
		}

		///<summary>
		///Gets or sets the value for Reason_code
		///</summary>
		public string Reason_code
		{
			get { return reason_code; }
			set { reason_code = value; }
		}

		///<summary>
		///Gets or sets the value for Remaining_settle
		///</summary>
		public decimal? Remaining_settle
		{
			get { return remaining_settle; }
			set { remaining_settle = value; }
		}

		///<summary>
		///Gets or sets the value for Transaction_entity
		///</summary>
		public string Transaction_entity
		{
			get { return transaction_entity; }
			set { transaction_entity = value; }
		}

		///<summary>
		///Gets or sets the value for Invoice
		///</summary>
		public string Invoice
		{
			get { return invoice; }
			set { invoice = value; }
		}

		///<summary>
		///Gets or sets the value for Memo
		///</summary>
		public string Memo
		{
			get { return memo; }
			set { memo = value; }
		}

		///<summary>
		///Gets or sets the value for Tax
		///</summary>
		public decimal? Tax
		{
			get { return tax; }
			set { tax = value; }
		}

		///<summary>
		///Gets or sets the value for Business
		///</summary>
		public string Business
		{
			get { return business; }
			set { business = value; }
		}

		///<summary>
		///Gets or sets the value for Item_name
		///</summary>
		public string Item_name
		{
			get { return item_name; }
			set { item_name = value; }
		}

		///<summary>
		///Gets or sets the value for Item_number
		///</summary>
		public string Item_number
		{
			get { return item_number; }
			set { item_number = value; }
		}

		///<summary>
		///Gets or sets the value for Quantity
		///</summary>
		public int? Quantity
		{
			get { return quantity; }
			set { quantity = value; }
		}

		///<summary>
		///Gets or sets the value for Receiver_email
		///</summary>
		public string Receiver_email
		{
			get { return receiver_email; }
			set { receiver_email = value; }
		}

		///<summary>
		///Gets or sets the value for Receiver_id
		///</summary>
		public string Receiver_id
		{
			get { return receiver_id; }
			set { receiver_id = value; }
		}

		///<summary>
		///Gets or sets the value for Address_city
		///</summary>
		public string Address_city
		{
			get { return address_city; }
			set { address_city = value; }
		}

		///<summary>
		///Gets or sets the value for Address_country
		///</summary>
		public string Address_country
		{
			get { return address_country; }
			set { address_country = value; }
		}

		///<summary>
		///Gets or sets the value for Address_country_code
		///</summary>
		public string Address_country_code
		{
			get { return address_country_code; }
			set { address_country_code = value; }
		}

		///<summary>
		///Gets or sets the value for Address_name
		///</summary>
		public string Address_name
		{
			get { return address_name; }
			set { address_name = value; }
		}

		///<summary>
		///Gets or sets the value for Address_state
		///</summary>
		public string Address_state
		{
			get { return address_state; }
			set { address_state = value; }
		}

		///<summary>
		///Gets or sets the value for Address_status
		///</summary>
		public string Address_status
		{
			get { return address_status; }
			set { address_status = value; }
		}

		///<summary>
		///Gets or sets the value for Address_street
		///</summary>
		public string Address_street
		{
			get { return address_street; }
			set { address_street = value; }
		}

		///<summary>
		///Gets or sets the value for Address_zip
		///</summary>
		public string Address_zip
		{
			get { return address_zip; }
			set { address_zip = value; }
		}

		///<summary>
		///Gets or sets the value for First_name
		///</summary>
		public string First_name
		{
			get { return first_name; }
			set { first_name = value; }
		}

		///<summary>
		///Gets or sets the value for Last_name
		///</summary>
		public string Last_name
		{
			get { return last_name; }
			set { last_name = value; }
		}

		///<summary>
		///Gets or sets the value for Payer_id
		///</summary>
		public string Payer_id
		{
			get { return payer_id; }
			set { payer_id = value; }
		}

		///<summary>
		///Gets or sets the value for Payer_status
		///</summary>
		public string Payer_status
		{
			get { return payer_status; }
			set { payer_status = value; }
		}

		///<summary>
		///Gets or sets the value for Residence_country
		///</summary>
		public string Residence_country
		{
			get { return residence_country; }
			set { residence_country = value; }
		}

		///<summary>
		///Gets or sets the value for Exchange_rate
		///</summary>
		public decimal? Exchange_rate
		{
			get { return exchange_rate; }
			set { exchange_rate = value; }
		}

		///<summary>
		///Gets or sets the value for Mc_fee
		///</summary>
		public decimal? Mc_fee
		{
			get { return mc_fee; }
			set { mc_fee = value; }
		}

		///<summary>
		///Gets or sets the value for Mc_gross
		///</summary>
		public decimal? Mc_gross
		{
			get { return mc_gross; }
			set { mc_gross = value; }
		}

		///<summary>
		///Gets or sets the value for Mc_handlingamount
		///</summary>
		public decimal? Mc_handlingamount
		{
			get { return mc_handlingamount; }
			set { mc_handlingamount = value; }
		}

		///<summary>
		///Gets or sets the value for Mc_shippingamount
		///</summary>
		public decimal? Mc_shippingamount
		{
			get { return mc_shippingamount; }
			set { mc_shippingamount = value; }
		}

		///<summary>
		///Gets or sets the value for Payment_fee
		///</summary>
		public decimal? Payment_fee
		{
			get { return payment_fee; }
			set { payment_fee = value; }
		}

		///<summary>
		///Gets or sets the value for Payment_gross
		///</summary>
		public decimal? Payment_gross
		{
			get { return payment_gross; }
			set { payment_gross = value; }
		}

		///<summary>
		///Gets or sets the value for Settle_amount
		///</summary>
		public decimal? Settle_amount
		{
			get { return settle_amount; }
			set { settle_amount = value; }
		}

		///<summary>
		///Gets or sets the value for Settle_currency
		///</summary>
		public string Settle_currency
		{
			get { return settle_currency; }
			set { settle_currency = value; }
		}

		///<summary>
		///Gets or sets the value for Subscr_date
		///</summary>
		public DateTime? Subscr_date
		{
			get { return subscr_date; }
			set { subscr_date = value; }
		}

		///<summary>
		///Gets or sets the value for Subscr_effective
		///</summary>
		public DateTime? Subscr_effective
		{
			get { return subscr_effective; }
			set { subscr_effective = value; }
		}

		///<summary>
		///Gets or sets the value for Period1
		///</summary>
		public string Period1
		{
			get { return period1; }
			set { period1 = value; }
		}

		///<summary>
		///Gets or sets the value for Period2
		///</summary>
		public string Period2
		{
			get { return period2; }
			set { period2 = value; }
		}

		///<summary>
		///Gets or sets the value for Period3
		///</summary>
		public string Period3
		{
			get { return period3; }
			set { period3 = value; }
		}

		///<summary>
		///Gets or sets the value for Amount1
		///</summary>
		public decimal? Amount1
		{
			get { return amount1; }
			set { amount1 = value; }
		}

		///<summary>
		///Gets or sets the value for Amount2
		///</summary>
		public decimal? Amount2
		{
			get { return amount2; }
			set { amount2 = value; }
		}

		///<summary>
		///Gets or sets the value for Amount3
		///</summary>
		public decimal? Amount3
		{
			get { return amount3; }
			set { amount3 = value; }
		}

		///<summary>
		///Gets or sets the value for Mc_amount1
		///</summary>
		public decimal? Mc_amount1
		{
			get { return mc_amount1; }
			set { mc_amount1 = value; }
		}

		///<summary>
		///Gets or sets the value for Mc_amount2
		///</summary>
		public decimal? Mc_amount2
		{
			get { return mc_amount2; }
			set { mc_amount2 = value; }
		}

		///<summary>
		///Gets or sets the value for Mc_amount3
		///</summary>
		public decimal? Mc_amount3
		{
			get { return mc_amount3; }
			set { mc_amount3 = value; }
		}

		///<summary>
		///Gets or sets the value for Mc_currency
		///</summary>
		public string Mc_currency
		{
			get { return mc_currency; }
			set { mc_currency = value; }
		}

		///<summary>
		///Gets or sets the value for Recurring
		///</summary>
		public bool? Recurring
		{
			get { return recurring; }
			set { recurring = value; }
		}

		///<summary>
		///Gets or sets the value for Reattempt
		///</summary>
		public bool? Reattempt
		{
			get { return reattempt; }
			set { reattempt = value; }
		}

		///<summary>
		///Gets or sets the value for Retry_at
		///</summary>
		public DateTime? Retry_at
		{
			get { return retry_at; }
			set { retry_at = value; }
		}

		///<summary>
		///Gets or sets the value for Recur_times
		///</summary>
		public int? Recur_times
		{
			get { return recur_times; }
			set { recur_times = value; }
		}

		///<summary>
		///Gets or sets the value for Username
		///</summary>
		public string Username
		{
			get { return username; }
			set { username = value; }
		}

		///<summary>
		///Gets or sets the value for Password
		///</summary>
		public string Password
		{
			get { return password; }
			set { password = value; }
		}

		///<summary>
		///Gets or sets the value for Subscr_id
		///</summary>
		public string Subscr_id
		{
			get { return subscr_id; }
			set { subscr_id = value; }
		}

		///<summary>
		///Gets or sets the value for Custom
		///</summary>
		public string Custom
		{
			get { return custom; }
			set { custom = value; }
		}
		
		#endregion

		#region Constructors

		public PayPalTransactionResponse()
		{
			WasNew = true;
			IsNew = true;
		}
		
		public PayPalTransactionResponse(Guid transactionID, string txn_id, string txn_type, decimal? auth_amount, string auth_id, DateTime? auth_exp, string auth_status, decimal? mc_gross_x, decimal? mc_handling_x, int? num_cart_items, string parent_txn_id, DateTime? payment_date, string payment_status, string payment_type, string pending_reason, string reason_code, decimal? remaining_settle, string transaction_entity, string invoice, string memo, decimal? tax, string business, string item_name, string item_number, int? quantity, string receiver_email, string receiver_id, string address_city, string address_country, string address_country_code, string address_name, string address_state, string address_status, string address_street, string address_zip, string first_name, string last_name, string payer_id, string payer_status, string residence_country, decimal? exchange_rate, decimal? mc_fee, decimal? mc_gross, decimal? mc_handlingamount, decimal? mc_shippingamount, decimal? payment_fee, decimal? payment_gross, decimal? settle_amount, string settle_currency, DateTime? subscr_date, DateTime? subscr_effective, string period1, string period2, string period3, decimal? amount1, decimal? amount2, decimal? amount3, decimal? mc_amount1, decimal? mc_amount2, decimal? mc_amount3, string mc_currency, bool? recurring, bool? reattempt, DateTime? retry_at, int? recur_times, string username, string password, string subscr_id, string custom)
		{
			this.transactionID = transactionID;
			this.txn_id = txn_id;
			this.txn_type = txn_type;
			this.auth_amount = auth_amount;
			this.auth_id = auth_id;
			this.auth_exp = auth_exp;
			this.auth_status = auth_status;
			this.mc_gross_x = mc_gross_x;
			this.mc_handling_x = mc_handling_x;
			this.num_cart_items = num_cart_items;
			this.parent_txn_id = parent_txn_id;
			this.payment_date = payment_date;
			this.payment_status = payment_status;
			this.payment_type = payment_type;
			this.pending_reason = pending_reason;
			this.reason_code = reason_code;
			this.remaining_settle = remaining_settle;
			this.transaction_entity = transaction_entity;
			this.invoice = invoice;
			this.memo = memo;
			this.tax = tax;
			this.business = business;
			this.item_name = item_name;
			this.item_number = item_number;
			this.quantity = quantity;
			this.receiver_email = receiver_email;
			this.receiver_id = receiver_id;
			this.address_city = address_city;
			this.address_country = address_country;
			this.address_country_code = address_country_code;
			this.address_name = address_name;
			this.address_state = address_state;
			this.address_status = address_status;
			this.address_street = address_street;
			this.address_zip = address_zip;
			this.first_name = first_name;
			this.last_name = last_name;
			this.payer_id = payer_id;
			this.payer_status = payer_status;
			this.residence_country = residence_country;
			this.exchange_rate = exchange_rate;
			this.mc_fee = mc_fee;
			this.mc_gross = mc_gross;
			this.mc_handlingamount = mc_handlingamount;
			this.mc_shippingamount = mc_shippingamount;
			this.payment_fee = payment_fee;
			this.payment_gross = payment_gross;
			this.settle_amount = settle_amount;
			this.settle_currency = settle_currency;
			this.subscr_date = subscr_date;
			this.subscr_effective = subscr_effective;
			this.period1 = period1;
			this.period2 = period2;
			this.period3 = period3;
			this.amount1 = amount1;
			this.amount2 = amount2;
			this.amount3 = amount3;
			this.mc_amount1 = mc_amount1;
			this.mc_amount2 = mc_amount2;
			this.mc_amount3 = mc_amount3;
			this.mc_currency = mc_currency;
			this.recurring = recurring;
			this.reattempt = reattempt;
			this.retry_at = retry_at;
			this.recur_times = recur_times;
			this.username = username;
			this.password = password;
			this.subscr_id = subscr_id;
			this.custom = custom;
			
			WasNew = true;
			IsNew = true;
		}
		
		public PayPalTransactionResponse(DataRow row)
		{
			if(row["TransactionID"] != DBNull.Value) transactionID = (Guid)row["TransactionID"];
			if(row["txn_id"] != DBNull.Value) txn_id = (string)row["txn_id"];
			if(row["txn_type"] != DBNull.Value) txn_type = (string)row["txn_type"];
			if(row["auth_amount"] != DBNull.Value) auth_amount = (decimal?)row["auth_amount"];
			if(row["auth_id"] != DBNull.Value) auth_id = (string)row["auth_id"];
			if(row["auth_exp"] != DBNull.Value) auth_exp = (DateTime?)row["auth_exp"];
			if(row["auth_status"] != DBNull.Value) auth_status = (string)row["auth_status"];
			if(row["mc_gross_x"] != DBNull.Value) mc_gross_x = (decimal?)row["mc_gross_x"];
			if(row["mc_handling_x"] != DBNull.Value) mc_handling_x = (decimal?)row["mc_handling_x"];
			if(row["num_cart_items"] != DBNull.Value) num_cart_items = (int?)row["num_cart_items"];
			if(row["parent_txn_id"] != DBNull.Value) parent_txn_id = (string)row["parent_txn_id"];
			if(row["payment_date"] != DBNull.Value) payment_date = (DateTime?)row["payment_date"];
			if(row["payment_status"] != DBNull.Value) payment_status = (string)row["payment_status"];
			if(row["payment_type"] != DBNull.Value) payment_type = (string)row["payment_type"];
			if(row["pending_reason"] != DBNull.Value) pending_reason = (string)row["pending_reason"];
			if(row["reason_code"] != DBNull.Value) reason_code = (string)row["reason_code"];
			if(row["remaining_settle"] != DBNull.Value) remaining_settle = (decimal?)row["remaining_settle"];
			if(row["transaction_entity"] != DBNull.Value) transaction_entity = (string)row["transaction_entity"];
			if(row["invoice"] != DBNull.Value) invoice = (string)row["invoice"];
			if(row["memo"] != DBNull.Value) memo = (string)row["memo"];
			if(row["tax"] != DBNull.Value) tax = (decimal?)row["tax"];
			if(row["business"] != DBNull.Value) business = (string)row["business"];
			if(row["item_name"] != DBNull.Value) item_name = (string)row["item_name"];
			if(row["item_number"] != DBNull.Value) item_number = (string)row["item_number"];
			if(row["quantity"] != DBNull.Value) quantity = (int?)row["quantity"];
			if(row["receiver_email"] != DBNull.Value) receiver_email = (string)row["receiver_email"];
			if(row["receiver_id"] != DBNull.Value) receiver_id = (string)row["receiver_id"];
			if(row["address_city"] != DBNull.Value) address_city = (string)row["address_city"];
			if(row["address_country"] != DBNull.Value) address_country = (string)row["address_country"];
			if(row["address_country_code"] != DBNull.Value) address_country_code = (string)row["address_country_code"];
			if(row["address_name"] != DBNull.Value) address_name = (string)row["address_name"];
			if(row["address_state"] != DBNull.Value) address_state = (string)row["address_state"];
			if(row["address_status"] != DBNull.Value) address_status = (string)row["address_status"];
			if(row["address_street"] != DBNull.Value) address_street = (string)row["address_street"];
			if(row["address_zip"] != DBNull.Value) address_zip = (string)row["address_zip"];
			if(row["first_name"] != DBNull.Value) first_name = (string)row["first_name"];
			if(row["last_name"] != DBNull.Value) last_name = (string)row["last_name"];
			if(row["payer_id"] != DBNull.Value) payer_id = (string)row["payer_id"];
			if(row["payer_status"] != DBNull.Value) payer_status = (string)row["payer_status"];
			if(row["residence_country"] != DBNull.Value) residence_country = (string)row["residence_country"];
			if(row["exchange_rate"] != DBNull.Value) exchange_rate = (decimal?)row["exchange_rate"];
			if(row["mc_fee"] != DBNull.Value) mc_fee = (decimal?)row["mc_fee"];
			if(row["mc_gross"] != DBNull.Value) mc_gross = (decimal?)row["mc_gross"];
			if(row["mc_handling#"] != DBNull.Value) mc_handlingamount = (decimal?)row["mc_handling#"];
			if(row["mc_shipping#"] != DBNull.Value) mc_shippingamount = (decimal?)row["mc_shipping#"];
			if(row["payment_fee"] != DBNull.Value) payment_fee = (decimal?)row["payment_fee"];
			if(row["payment_gross"] != DBNull.Value) payment_gross = (decimal?)row["payment_gross"];
			if(row["settle_amount"] != DBNull.Value) settle_amount = (decimal?)row["settle_amount"];
			if(row["settle_currency"] != DBNull.Value) settle_currency = (string)row["settle_currency"];
			if(row["subscr_date"] != DBNull.Value) subscr_date = (DateTime?)row["subscr_date"];
			if(row["subscr_effective"] != DBNull.Value) subscr_effective = (DateTime?)row["subscr_effective"];
			if(row["period1"] != DBNull.Value) period1 = (string)row["period1"];
			if(row["period2"] != DBNull.Value) period2 = (string)row["period2"];
			if(row["period3"] != DBNull.Value) period3 = (string)row["period3"];
			if(row["amount1"] != DBNull.Value) amount1 = (decimal?)row["amount1"];
			if(row["amount2"] != DBNull.Value) amount2 = (decimal?)row["amount2"];
			if(row["amount3"] != DBNull.Value) amount3 = (decimal?)row["amount3"];
			if(row["mc_amount1"] != DBNull.Value) mc_amount1 = (decimal?)row["mc_amount1"];
			if(row["mc_amount2"] != DBNull.Value) mc_amount2 = (decimal?)row["mc_amount2"];
			if(row["mc_amount3"] != DBNull.Value) mc_amount3 = (decimal?)row["mc_amount3"];
			if(row["mc_currency"] != DBNull.Value) mc_currency = (string)row["mc_currency"];
			if(row["recurring"] != DBNull.Value) recurring = (bool?)row["recurring"];
			if(row["reattempt"] != DBNull.Value) reattempt = (bool?)row["reattempt"];
			if(row["retry_at"] != DBNull.Value) retry_at = (DateTime?)row["retry_at"];
			if(row["recur_times"] != DBNull.Value) recur_times = (int?)row["recur_times"];
			if(row["username"] != DBNull.Value) username = (string)row["username"];
			if(row["password"] != DBNull.Value) password = (string)row["password"];
			if(row["subscr_id"] != DBNull.Value) subscr_id = (string)row["subscr_id"];
			if(row["custom"] != DBNull.Value) custom = (string)row["custom"];

			WasNew = false;
			IsNew = false;
		}

		#endregion
		
		#region Saving and Loading
		
		public Guid Save()
		{
			string procName = IsNew ? "PayPalTransactionResponse_Insert" : "PayPalTransactionResponse_UpdateExplicit";
			IDbCommand cmd = Database.Main.CreateCommand(procName, CommandType.StoredProcedure);
			Database.Main.AddParameter(cmd, "@TransactionID", transactionID, DbType.Guid);
			Database.Main.AddParameter(cmd, "@txn_id", txn_id, DbType.String);
			Database.Main.AddParameter(cmd, "@txn_type", txn_type, DbType.String);
			Database.Main.AddParameter(cmd, "@auth_amount", auth_amount, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@auth_id", auth_id, DbType.String);
			Database.Main.AddParameter(cmd, "@auth_exp", auth_exp, DbType.DateTime);
			Database.Main.AddParameter(cmd, "@auth_status", auth_status, DbType.String);
			Database.Main.AddParameter(cmd, "@mc_gross_x", mc_gross_x, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_handling_x", mc_handling_x, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@num_cart_items", num_cart_items, DbType.Int32);
			Database.Main.AddParameter(cmd, "@parent_txn_id", parent_txn_id, DbType.String);
			Database.Main.AddParameter(cmd, "@payment_date", payment_date, DbType.DateTime);
			Database.Main.AddParameter(cmd, "@payment_status", payment_status, DbType.String);
			Database.Main.AddParameter(cmd, "@payment_type", payment_type, DbType.String);
			Database.Main.AddParameter(cmd, "@pending_reason", pending_reason, DbType.String);
			Database.Main.AddParameter(cmd, "@reason_code", reason_code, DbType.String);
			Database.Main.AddParameter(cmd, "@remaining_settle", remaining_settle, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@transaction_entity", transaction_entity, DbType.String);
			Database.Main.AddParameter(cmd, "@invoice", invoice, DbType.String);
			Database.Main.AddParameter(cmd, "@memo", memo, DbType.String);
			Database.Main.AddParameter(cmd, "@tax", tax, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@business", business, DbType.String);
			Database.Main.AddParameter(cmd, "@item_name", item_name, DbType.String);
			Database.Main.AddParameter(cmd, "@item_number", item_number, DbType.String);
			Database.Main.AddParameter(cmd, "@quantity", quantity, DbType.Int32);
			Database.Main.AddParameter(cmd, "@receiver_email", receiver_email, DbType.String);
			Database.Main.AddParameter(cmd, "@receiver_id", receiver_id, DbType.String);
			Database.Main.AddParameter(cmd, "@address_city", address_city, DbType.String);
			Database.Main.AddParameter(cmd, "@address_country", address_country, DbType.String);
			Database.Main.AddParameter(cmd, "@address_country_code", address_country_code, DbType.String);
			Database.Main.AddParameter(cmd, "@address_name", address_name, DbType.String);
			Database.Main.AddParameter(cmd, "@address_state", address_state, DbType.String);
			Database.Main.AddParameter(cmd, "@address_status", address_status, DbType.String);
			Database.Main.AddParameter(cmd, "@address_street", address_street, DbType.String);
			Database.Main.AddParameter(cmd, "@address_zip", address_zip, DbType.String);
			Database.Main.AddParameter(cmd, "@first_name", first_name, DbType.String);
			Database.Main.AddParameter(cmd, "@last_name", last_name, DbType.String);
			Database.Main.AddParameter(cmd, "@payer_id", payer_id, DbType.String);
			Database.Main.AddParameter(cmd, "@payer_status", payer_status, DbType.String);
			Database.Main.AddParameter(cmd, "@residence_country", residence_country, DbType.String);
			Database.Main.AddParameter(cmd, "@exchange_rate", exchange_rate, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_fee", mc_fee, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_gross", mc_gross, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_handling#", mc_handlingamount, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_shipping#", mc_shippingamount, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@payment_fee", payment_fee, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@payment_gross", payment_gross, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@settle_amount", settle_amount, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@settle_currency", settle_currency, DbType.String);
			Database.Main.AddParameter(cmd, "@subscr_date", subscr_date, DbType.DateTime);
			Database.Main.AddParameter(cmd, "@subscr_effective", subscr_effective, DbType.DateTime);
			Database.Main.AddParameter(cmd, "@period1", period1, DbType.String);
			Database.Main.AddParameter(cmd, "@period2", period2, DbType.String);
			Database.Main.AddParameter(cmd, "@period3", period3, DbType.String);
			Database.Main.AddParameter(cmd, "@amount1", amount1, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@amount2", amount2, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@amount3", amount3, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_amount1", mc_amount1, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_amount2", mc_amount2, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_amount3", mc_amount3, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_currency", mc_currency, DbType.String);
			Database.Main.AddParameter(cmd, "@recurring", recurring, DbType.Boolean);
			Database.Main.AddParameter(cmd, "@reattempt", reattempt, DbType.Boolean);
			Database.Main.AddParameter(cmd, "@retry_at", retry_at, DbType.DateTime);
			Database.Main.AddParameter(cmd, "@recur_times", recur_times, DbType.Int32);
			Database.Main.AddParameter(cmd, "@username", username, DbType.String);
			Database.Main.AddParameter(cmd, "@password", password, DbType.String);
			Database.Main.AddParameter(cmd, "@subscr_id", subscr_id, DbType.String);
			Database.Main.AddParameter(cmd, "@custom", custom, DbType.String);
			cmd.ExecuteNonQuery();
			SetSaved();
			return transactionID;
		}

		public static void Delete(Guid transactionID)
		{
			IDbCommand cmd = Database.Main.CreateCommand("PayPalTransactionResponse_Delete", CommandType.StoredProcedure);
			Database.Main.AddParameter(cmd, "@TransactionID", transactionID);
			cmd.ExecuteNonQuery();
		}

		/// <summary>
		/// Attempts to load an instance of PayPalTransactionResponse from the supplied transactionID.
		/// An exception is thrown if the record does not exist.
		/// </summary>
		public static PayPalTransactionResponse Load(Guid transactionID)
		{
			Database.Main.RememberOpenState();
			IDbCommand cmd = Database.Main.CreateCommand("PayPalTransactionResponse_Select", CommandType.StoredProcedure);
			Database.Main.AddParameter(cmd, "@TransactionID", transactionID);
			DataSet ds = Database.Main.GetDataSet(cmd);
			Database.Main.CloseIfWasntOpen();
			if(ds.Tables[0].Rows.Count == 0)
				throw new SprocketException("Cannot load PayPalTransactionResponse with TransactionID of " + transactionID + ". Record does not exist.");
			return new PayPalTransactionResponse(ds.Tables[0].Rows[0]);
		}

		/// <summary>
		/// Attempts to load an instance of PayPalTransactionResponse from the supplied transactionID.
		/// If the record does not exist, null is returned.
		/// </summary>
		public static PayPalTransactionResponse TryLoad(Guid transactionID)
		{
			Database.Main.RememberOpenState();
			IDbCommand cmd = Database.Main.CreateCommand("PayPalTransactionResponse_Select", CommandType.StoredProcedure);
			Database.Main.AddParameter(cmd, "@TransactionID", transactionID);
			DataSet ds = Database.Main.GetDataSet(cmd);
			Database.Main.CloseIfWasntOpen();
			if(ds.Tables[0].Rows.Count == 0)
				return null;
			return new PayPalTransactionResponse(ds.Tables[0].Rows[0]);
		}

		public static PayPalTransactionResponse[] Load(DataTable payPalTransactionResponseDataTable)
		{
			PayPalTransactionResponse[] arr = new PayPalTransactionResponse[payPalTransactionResponseDataTable.Rows.Count];
			for(int i=0; i<payPalTransactionResponseDataTable.Rows.Count; i++)
				arr[i] = new PayPalTransactionResponse(payPalTransactionResponseDataTable.Rows[i]);
			return arr;
		}
		
		public static Dictionary<Guid, PayPalTransactionResponse> Filter(Guid? transactionID, string txn_id, string txn_type, decimal? auth_amount, string auth_id, DateTime? auth_exp, string auth_status, decimal? mc_gross_x, decimal? mc_handling_x, int? num_cart_items, string parent_txn_id, DateTime? payment_date, string payment_status, string payment_type, string pending_reason, string reason_code, decimal? remaining_settle, string transaction_entity, string invoice, string memo, decimal? tax, string business, string item_name, string item_number, int? quantity, string receiver_email, string receiver_id, string address_city, string address_country, string address_country_code, string address_name, string address_state, string address_status, string address_street, string address_zip, string first_name, string last_name, string payer_id, string payer_status, string residence_country, decimal? exchange_rate, decimal? mc_fee, decimal? mc_gross, decimal? mc_handlingamount, decimal? mc_shippingamount, decimal? payment_fee, decimal? payment_gross, decimal? settle_amount, string settle_currency, DateTime? subscr_date, DateTime? subscr_effective, string period1, string period2, string period3, decimal? amount1, decimal? amount2, decimal? amount3, decimal? mc_amount1, decimal? mc_amount2, decimal? mc_amount3, string mc_currency, bool? recurring, bool? reattempt, DateTime? retry_at, int? recur_times, string username, string password, string subscr_id, string custom)
		{
			Database.Main.RememberOpenState();
			Dictionary<Guid, PayPalTransactionResponse> results = new Dictionary<Guid, PayPalTransactionResponse>();
			IDbCommand cmd = Database.Main.CreateCommand("PayPalTransactionResponse_Filter", CommandType.StoredProcedure);
			Database.Main.AddParameter(cmd, "@TransactionID", transactionID, DbType.Guid);
			Database.Main.AddParameter(cmd, "@txn_id", txn_id, DbType.String);
			Database.Main.AddParameter(cmd, "@txn_type", txn_type, DbType.String);
			Database.Main.AddParameter(cmd, "@auth_amount", auth_amount, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@auth_id", auth_id, DbType.String);
			Database.Main.AddParameter(cmd, "@auth_exp", auth_exp, DbType.DateTime);
			Database.Main.AddParameter(cmd, "@auth_status", auth_status, DbType.String);
			Database.Main.AddParameter(cmd, "@mc_gross_x", mc_gross_x, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_handling_x", mc_handling_x, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@num_cart_items", num_cart_items, DbType.Int32);
			Database.Main.AddParameter(cmd, "@parent_txn_id", parent_txn_id, DbType.String);
			Database.Main.AddParameter(cmd, "@payment_date", payment_date, DbType.DateTime);
			Database.Main.AddParameter(cmd, "@payment_status", payment_status, DbType.String);
			Database.Main.AddParameter(cmd, "@payment_type", payment_type, DbType.String);
			Database.Main.AddParameter(cmd, "@pending_reason", pending_reason, DbType.String);
			Database.Main.AddParameter(cmd, "@reason_code", reason_code, DbType.String);
			Database.Main.AddParameter(cmd, "@remaining_settle", remaining_settle, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@transaction_entity", transaction_entity, DbType.String);
			Database.Main.AddParameter(cmd, "@invoice", invoice, DbType.String);
			Database.Main.AddParameter(cmd, "@memo", memo, DbType.String);
			Database.Main.AddParameter(cmd, "@tax", tax, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@business", business, DbType.String);
			Database.Main.AddParameter(cmd, "@item_name", item_name, DbType.String);
			Database.Main.AddParameter(cmd, "@item_number", item_number, DbType.String);
			Database.Main.AddParameter(cmd, "@quantity", quantity, DbType.Int32);
			Database.Main.AddParameter(cmd, "@receiver_email", receiver_email, DbType.String);
			Database.Main.AddParameter(cmd, "@receiver_id", receiver_id, DbType.String);
			Database.Main.AddParameter(cmd, "@address_city", address_city, DbType.String);
			Database.Main.AddParameter(cmd, "@address_country", address_country, DbType.String);
			Database.Main.AddParameter(cmd, "@address_country_code", address_country_code, DbType.String);
			Database.Main.AddParameter(cmd, "@address_name", address_name, DbType.String);
			Database.Main.AddParameter(cmd, "@address_state", address_state, DbType.String);
			Database.Main.AddParameter(cmd, "@address_status", address_status, DbType.String);
			Database.Main.AddParameter(cmd, "@address_street", address_street, DbType.String);
			Database.Main.AddParameter(cmd, "@address_zip", address_zip, DbType.String);
			Database.Main.AddParameter(cmd, "@first_name", first_name, DbType.String);
			Database.Main.AddParameter(cmd, "@last_name", last_name, DbType.String);
			Database.Main.AddParameter(cmd, "@payer_id", payer_id, DbType.String);
			Database.Main.AddParameter(cmd, "@payer_status", payer_status, DbType.String);
			Database.Main.AddParameter(cmd, "@residence_country", residence_country, DbType.String);
			Database.Main.AddParameter(cmd, "@exchange_rate", exchange_rate, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_fee", mc_fee, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_gross", mc_gross, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_handling#", mc_handlingamount, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_shipping#", mc_shippingamount, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@payment_fee", payment_fee, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@payment_gross", payment_gross, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@settle_amount", settle_amount, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@settle_currency", settle_currency, DbType.String);
			Database.Main.AddParameter(cmd, "@subscr_date", subscr_date, DbType.DateTime);
			Database.Main.AddParameter(cmd, "@subscr_effective", subscr_effective, DbType.DateTime);
			Database.Main.AddParameter(cmd, "@period1", period1, DbType.String);
			Database.Main.AddParameter(cmd, "@period2", period2, DbType.String);
			Database.Main.AddParameter(cmd, "@period3", period3, DbType.String);
			Database.Main.AddParameter(cmd, "@amount1", amount1, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@amount2", amount2, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@amount3", amount3, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_amount1", mc_amount1, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_amount2", mc_amount2, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_amount3", mc_amount3, DbType.Decimal);
			Database.Main.AddParameter(cmd, "@mc_currency", mc_currency, DbType.String);
			Database.Main.AddParameter(cmd, "@recurring", recurring, DbType.Boolean);
			Database.Main.AddParameter(cmd, "@reattempt", reattempt, DbType.Boolean);
			Database.Main.AddParameter(cmd, "@retry_at", retry_at, DbType.DateTime);
			Database.Main.AddParameter(cmd, "@recur_times", recur_times, DbType.Int32);
			Database.Main.AddParameter(cmd, "@username", username, DbType.String);
			Database.Main.AddParameter(cmd, "@password", password, DbType.String);
			Database.Main.AddParameter(cmd, "@subscr_id", subscr_id, DbType.String);
			Database.Main.AddParameter(cmd, "@custom", custom, DbType.String);
			DataSet ds = Database.Main.GetDataSet(cmd);
			Database.Main.CloseIfWasntOpen();
			foreach(DataRow row in ds.Tables[0].Rows)
			{
				PayPalTransactionResponse o = new PayPalTransactionResponse(row);
				results.Add(o.transactionID, o);
			}
			return results;
		}

		/// <summary>
		/// Populates the class fields with values derived from strings. Use this method
		/// to take a list of string values from a fieldname/value collection and assign
		/// them to their native fields in the class.
		/// </summary>
		public void Populate(IDictionary values)
		{
			foreach (object key in values.Keys)
				Populate(key.ToString(), values[key].ToString());
		}

		/// <summary>
		/// Populates the class fields with values derived from strings. Use this method
		/// to take a list of string values from a fieldname/value collection and assign
		/// them to their native fields in the class.
		/// </summary>
		public void Populate(NameValueCollection values)
		{
			foreach (string key in values.Keys)
				Populate(key, values[key].ToString());
		}

		/// <summary>
		/// Populates the class fields with values derived from strings. Use this method
		/// to take a list of string values from a fieldname/value collection and assign
		/// them to their native fields in the class.
		/// </summary>
		public bool Populate(string fieldName, string value)
		{
			switch (fieldName)
			{
				case "TransactionID": if(value.Length > 0) transactionID = new Guid(value); return true;
				case "txn_id": txn_id = value; return true;
				case "txn_type": txn_type = value; return true;
				case "auth_amount": if(value.Length > 0) auth_amount = Decimal.Parse(value); return true;
				case "auth_id": auth_id = value; return true;
				case "auth_exp": if(value.Length > 0) auth_exp = ParseDateTime(value); return true;
				case "auth_status": auth_status = value; return true;
				case "mc_gross_x": if(value.Length > 0) mc_gross_x = Decimal.Parse(value); return true;
				case "mc_handling_x": if(value.Length > 0) mc_handling_x = Decimal.Parse(value); return true;
				case "num_cart_items": if(value.Length > 0) num_cart_items = Int32.Parse(value); return true;
				case "parent_txn_id": parent_txn_id = value; return true;
				case "payment_date": if(value.Length > 0) payment_date = ParseDateTime(value); return true;
				case "payment_status": payment_status = value; return true;
				case "payment_type": payment_type = value; return true;
				case "pending_reason": pending_reason = value; return true;
				case "reason_code": reason_code = value; return true;
				case "remaining_settle": if(value.Length > 0) remaining_settle = Decimal.Parse(value); return true;
				case "transaction_entity": transaction_entity = value; return true;
				case "invoice": invoice = value; return true;
				case "memo": memo = value; return true;
				case "tax": if(value.Length > 0) tax = Decimal.Parse(value); return true;
				case "business": business = value; return true;
				case "item_name": item_name = value; return true;
				case "item_number": item_number = value; return true;
				case "quantity": if(value.Length > 0) quantity = Int32.Parse(value); return true;
				case "receiver_email": receiver_email = value; return true;
				case "receiver_id": receiver_id = value; return true;
				case "address_city": address_city = value; return true;
				case "address_country": address_country = value; return true;
				case "address_country_code": address_country_code = value; return true;
				case "address_name": address_name = value; return true;
				case "address_state": address_state = value; return true;
				case "address_status": address_status = value; return true;
				case "address_street": address_street = value; return true;
				case "address_zip": address_zip = value; return true;
				case "first_name": first_name = value; return true;
				case "last_name": last_name = value; return true;
				case "payer_id": payer_id = value; return true;
				case "payer_status": payer_status = value; return true;
				case "residence_country": residence_country = value; return true;
				case "exchange_rate": if(value.Length > 0) exchange_rate = Decimal.Parse(value); return true;
				case "mc_fee": if(value.Length > 0) mc_fee = Decimal.Parse(value); return true;
				case "mc_gross": if(value.Length > 0) mc_gross = Decimal.Parse(value); return true;
				case "mc_handling#": if(value.Length > 0) mc_handlingamount = Decimal.Parse(value); return true;
				case "mc_shipping#": if(value.Length > 0) mc_shippingamount = Decimal.Parse(value); return true;
				case "payment_fee": if(value.Length > 0) payment_fee = Decimal.Parse(value); return true;
				case "payment_gross": if(value.Length > 0) payment_gross = Decimal.Parse(value); return true;
				case "settle_amount": if(value.Length > 0) settle_amount = Decimal.Parse(value); return true;
				case "settle_currency": settle_currency = value; return true;
				case "subscr_date": if(value.Length > 0) subscr_date = ParseDateTime(value); return true;
				case "subscr_effective": if(value.Length > 0) subscr_effective = ParseDateTime(value); return true;
				case "period1": period1 = value; return true;
				case "period2": period2 = value; return true;
				case "period3": period3 = value; return true;
				case "amount1": if(value.Length > 0) amount1 = Decimal.Parse(value); return true;
				case "amount2": if(value.Length > 0) amount2 = Decimal.Parse(value); return true;
				case "amount3": if(value.Length > 0) amount3 = Decimal.Parse(value); return true;
				case "mc_amount1": if(value.Length > 0) mc_amount1 = Decimal.Parse(value); return true;
				case "mc_amount2": if(value.Length > 0) mc_amount2 = Decimal.Parse(value); return true;
				case "mc_amount3": if(value.Length > 0) mc_amount3 = Decimal.Parse(value); return true;
				case "mc_currency": mc_currency = value; return true;
				case "recurring": if(value.Length > 0) recurring = Utilities.BoolFromString(value); return true;
				case "reattempt": if(value.Length > 0) reattempt = Utilities.BoolFromString(value); return true;
				case "retry_at": if(value.Length > 0) retry_at = ParseDateTime(value); return true;
				case "recur_times": if(value.Length > 0) recur_times = Int32.Parse(value); return true;
				case "username": username = value; return true;
				case "password": password = value; return true;
				case "subscr_id": subscr_id = value; return true;
				case "custom": custom = value; return true;
				default:
					return false;
			}
		}
		
		private DateTime ParseDateTime(string value)
		{
			string fmt = "HH:mm:ss MMM dd, yyyy";
			if (value.Length > 4 && value[value.Length - 4] == ' ')
				fmt += value.Substring(value.Length - 4, 4);
			return DateTime.ParseExact(value, new string[] { fmt, "r", "u", "s", "U", "y" }, new CultureInfo("en-US", true), DateTimeStyles.None);
		}

		#endregion
	}
}